### ISSUE TITLE
The destination directory "bin" cannot be found.

### ISSUE THREAD

**Issue by MisayaZ** [zhangliliang/RPN_BF#1]
when I run faster_rcnn_build, I got the erro
The destination directory "bin" cannot be found.

Error in faster_rcnn_build (line 13)
  mex -O -outdir bin ...

**Comment by chelicynly** [comment]
I got the same error. Could you help me to fix it?

**Comment by MisayaZ** [comment]
@chelicynly  I think you should make the dir by yourself
