### ISSUE TITLE
Error in running the script_rpn_bf_pedestrian_VGG16_caltech_demo

### ISSUE THREAD

**Issue by myhandson** [zhangliliang/RPN_BF#14]
[libprotobuf ERROR google/protobuf/text_format.cc:245] Error parsing text-format caffe.NetParameter: 534:30: Message type "caffe.ConvolutionParameter" has no field named "filter_stride".
WARNING: Logging before InitGoogleLogging() is written to STDERR
F1019 18:58:15.951474  2862 upgrade_proto.cpp:928] Check failed: ReadProtoFromTextFile(param_file, param) Failed to parse NetParameter file: /home/handson/RPN_BF/output/VGG16_caltech_final/rpn_test.prototxt
**\* Check failure stack trace: ***
已杀死
handson@handson-Aspire-TC-705:~$ 

I dont use GPU.Could you please give some advice? Thanks a lot!

**Comment by zhangliliang** [comment]
Hi,

You might try to compling this caffe version (https://github.com/zhangliliang/caffe), which support the atrous trick.
