### ISSUE TITLE
Caltech demo builds and runs but doesn't detect pedestrians

### ISSUE THREAD

**Issue by JimKlingshirn** [zhangliliang/RPN_BF#15]
Hi,

Thanks for sharing your code.

I've  downloaded VGG16_caltech_final.zip, and built the code.  When I run the demo, there are no pedestrians detected.   The scores produced by the adaboost classifier are all very low (essentially zero). The region proposal values and scores seem reasonable.  When I examine the "feat" vectors, most of the values are exactly zero.  I'm guessing this is the  problem.  Any suggestions for debugging this would be very welcome.

My setup:  Ubuntu 14.04,  Cuda 8.0, CuDNN version 2, Nvidia GTX 1080, Matlab R2016b

Many thanks

**Comment by zhangliliang** [comment]
Hi,

The md5sum for the VGG16_caltech_final.zip should be equaled to df9e1aed34784a6be5f57ceb4a82ed03 .

Is it correct for you?

If so, I consider the main problem might be the different environment we used.

It might be solved after compling this mex file for matlab via this caffe version(https://github.com/zhangliliang/caffe/tree/RPN_BF) in your computer. Then replace that mex in the external/caffe/matlab/caffe_faster_rcnn/

**Comment by JimKlingshirn** [comment]
That md5sum is correct for me.   

I did compile the mex file.  In fact I never even tried the mex file you supplied.  I'll try that.  

I also suspect that I have a compatibility problem with my GPU/matlab/cuda combination.  Apparently Matlab R2016b doesn't support Cuda 8.0.  I'm going to try again with Cuda 7.5.

Thanks!

**Comment by JimKlingshirn** [comment]
It's working now.  Instead of  a new GPU (GTX 1080) with Cuda 8.0, I'm using an older Titan X with Cuda 7.5 and CuDNN version 2.  

Thanks
