### ISSUE TITLE
error when running script_rpn_pedestrian_VGG16_caltech.m for training rpn

### ISSUE THREAD

**Issue by gy1874** [zhangliliang/RPN_BF#16]
the error reads like this:

Caught "std::exception" Exception message is:
CHECK failed: generated_database_->Add(encoded_file_descriptor, size): 

Thanks very much! @zhangliliang

**Comment by zhangliliang** [comment]
HI,

It might be a bug when try to run the script in the matlab for twice.
If so, the message might be disappear after close and restart the matlab.

**Comment by gy1874** [comment]
Thanks a lot for your reply!
It seems the only way to figure it out.

**Comment by gy1874** [comment]
I also got stuck in training rpn.
Could you please have a look?
![image](https://cloud.githubusercontent.com/assets/18019841/19895279/16798324-a08b-11e6-9c6e-e6e87c95cec2.png)
Thanks very much! @zhangliliang

**Comment by zhangliliang** [comment]
Hi,

It might be something wrong when preparing the data and the imdb.

**Comment by gy1874** [comment]
Thanks a lot for your reply!
I‘m trying to fix it.

**Comment by gy1874** [comment]
Then meet another error.
Could you please have a look?

Preparing training data...total (2) = nonempty (2) + empty (0)
Starting parallel pool (parpool) using the 'local' profile ... connected to 12 workers.
Done.
Preparing validation data...total (2) = nonempty (2) + empty (0)
Done.
Error using arrayfun
Sparse Arrays are not supported. See SPFUN.

Error in proposal_train_caltech>generate_random_minibatch (line 195)
            empty_image_inds = arrayfun(@(x) sum(x.bbox_targets{1}(:, 1)==1) == 0, image_roidb, 'UniformOutput', true);

Thanks very much! @zhangliliang

**Comment by gy1874** [comment]
When the folder '.imdb/cache' is deleted before training, the problem seems to be fixed.
