### ISSUE TITLE
Question about machine

### ISSUE THREAD

**Issue by SummerTrains** [zhangliliang/RPN_BF#18]
First of all, thank you for your job!
However, when I run script_rpn_pedestrian_VGG16_caltech.m , my computer jamed and  can not do anything, staying in the stage "stage one RPN"!  Then, I waited for about 1 hour, it's still jamed.  
So I just want to ask the minimum requirement about machine. 
Here is my machine : One Titan x GPU; 32G memory. Is enough for this experiment? 
Thank you very much!

**Comment by zhangliliang** [comment]
Hi,

Actually the problem might lie on the CPU memory (not the GPU memory).

The RPN need to pre-compute and save all the anchors for all images, and store them in the memory during the training time.

The Caltech 10x dataset contains 4w+ images, and it might need a large memory.

Thus, it might help when reduce the training data, e.g. reduce to Caltech 3x or Caltech 5x.

**Comment by SummerTrains** [comment]
@zhangliliang Thank you!
I'm reading your code. 
So which configuration can change Caltech 10x to Caltech 5x or 3x ? Can you tell me now ?
Thank you!

**Comment by zhangliliang** [comment]
Hi,

Change the skip in the extract_img_anno.m.

Skip = 3 coresponds to caltech10x， skip = 6 corespond a to caltech5x.
