### ISSUE TITLE
How to deal with ground truths annotated as "people" or "person?"

### ISSUE THREAD

**Issue by yijunCai** [zhangliliang/RPN_BF#23]
Hi @zhangliliang 
Sorry to bother you again，but I'm wondering how you dealed with ground truths annotated as "people" or "person?", since these ground truths may introduce some noise during training. I prefer simply ignore them.
Thanks a lot!

**Comment by zhangliliang** [comment]
Yes. You are right.

I use this few lines in the  `roidb_from_caltech.m` for extracting the groundtruth.

```
addpath(genpath('./external/code3.2.1'));
pLoad={'lbls',{'person'},'ilbls',{'people'},'squarify',{3,.41}};
pLoad = [pLoad 'hRng',[50 inf], 'vRng',[1 1] ];
```

It means that we only care about the "person" annotations which arefully visible and more than 50 pixels tall. 

These few lines are modified from the ACF methods in the dollar toolbox. You might refer to that code or their T-PAMI paper for more details.

**Comment by yijunCai** [comment]
Got it. Thank you so much!
