### ISSUE TITLE
error while training the RPN

### ISSUE THREAD

**Issue by Yezipiaomu** [zhangliliang/RPN_BF#26]
I am very sorry to disturb you !
I cannot find the solution

when I run script_rpn_pedestrian_VGG16_caltech.m
the error comes as below:
----------------------------------------------------------------------------
Warrning: no windows proposal is loaded !
Reference to non-existent field 'sizes'.

Error in roidb_from_caltech (line 52)
  height = imdb.sizes(1,1);

Error in Dataset.caltech_test (line 9)
        dataset.roidb_test    = dataset.imdb_test.roidb_func(dataset.imdb_test, false);

Error in script_rpn_pedestrian_VGG16_caltech (line 32)
dataset                     = Dataset.caltech_test(dataset, 'test');

I am very appreciate you to answer this!!!!

**Comment by zhangliliang** [comment]
Might be solve after removing the `imdb\cache` folder, and then re-run the script for re-generate the imdb and roidb.
