### ISSUE TITLE
how to train on other dataset 

### ISSUE THREAD

**Issue by shllhs** [zhangliliang/RPN_BF#27]
hello @zhangliliang ,I want to train the model on other dataset like INRIA or ETH , but there are only code for caltech , how should I add the training code? Thank you very much!

**Comment by zhangliliang** [comment]
This repo mainly merge the data preparing and training code for Caltech dataset into the [original Faster RCNN repo](https://github.com/ShaoqingRen/faster_rcnn). 

Generally, almost all the relevant script are named with "_caltech" suffix, e.g. imdb_from_caltech.m, script_rpn_pedestrian_VGG16_caltech.m, etc.

Thus, you might read these scripts and modified them as some scripts which could fit into other dataset.

**Comment by shllhs** [comment]
got it,thank you!

**Comment by Falmi** [comment]
@shllhs @zhangliliang  , could you share how you successfully trained on other data set, pls?
