### ISSUE TITLE
Is there any code for using faster-rcnn training for Caltech

### ISSUE THREAD

**Issue by Yezipiaomu** [zhangliliang/RPN_BF#28]
Hello,
     sorry to disturb you ,have you make the test for uisng the faster-rcnn in Caltech。i know your paper'title is "Is faster rcnn done well for the .",do you make the test. If you have ,would you copy an code to the github,Thank you !

**Comment by zhangliliang** [comment]
Hi,

Currently I am too busy to maintain this repo.
Might consider add the faster-rcnn code into this repo afterwards.
