### ISSUE TITLE
Computer crashed while running script_rpn_pedestrian_VGG16_caltech.m for training rpn

### ISSUE THREAD

**Issue by YangXiangChen** [zhangliliang/RPN_BF#29]
Hello, I'm sorry to disturb you. I'm trying to re-implement the code and I have some questions for compiling and training the RPN. 

For the compiling part, I'm not sure if I'm doing it right. First, I downloaded and compiled the [Caffe,](https://github.com/zhangliliang/caffe/tree/RPN_BF) which is mentiond in the Requirements section. Second, I run the rpn_bf_build.m and startup.m and also the script_rpn_bf_pedestrian_VGG16_caltech_demo.m. The demo seems succeed, but I'm wondering is that right or not for using rpn_bf_build.m instead of faster_rcnn_build.m.

For training the RPN part, I have successfully extract images and create the annos. I also downloaded the pre-trained model from website, and unzip in the repo folder. But I have a problem on running the script_rpn_pedestrian_VGG16_caltech.m, which is that my computer will crash without warning at "preparing data" part after running for 10 or 20 minutes. My environment is ubuntu 14.04 and Nvidia Titan X, with cuda 7.5 and cudnn v3. I have noticed that even the code shows "use GPU 1", which is Titan X, the loading of my GPU memory won't increase(I use the "nvidia-smi" command in terminal to see the memory usage), but the RAM loading(system monitor) of my pc will increase and then it crashed.

Could you please give some advice? Thanks a lot!

**Comment by zhangliliang** [comment]
Hi, 

The problem might be that the RPN need to pre-compute all the anchors for all the images in the dataset, and then storage them in the memory.

Actually, my computer has 64G memory, thus it's not a problem for me.

Thus, you might try to reduce the training data from Caltech 10x to Caltech 3x via modifying the parameters in the extract_img_anno.m.

Also, changeing `parfor` to `for` in the "preparing data" step could also save memory usage.

**Comment by YangXiangChen** [comment]
@zhangliliang Thanks for your advice! I will give a try.
