### ISSUE TITLE
Warrning: no windows proposal is loaded !: script_rpn_pedestrian_VGG16_caltech

### ISSUE THREAD

**Issue by noranart** [zhangliliang/RPN_BF#4]
Hi,

I ran script_rpn_pedestrian_VGG16_caltech and received the error message as following.

`Loading region proposals...done
Warrning: no windows proposal is loaded !
Reference to non-existent field 'sizes'.

Error in roidb_from_caltech (line 52)
  height = imdb.sizes(1,1);

Error in Dataset.caltech_trainval>@(x)x.roidb_func(x,false) (line 6)
        dataset.roidb_train   = cellfun(@(x) x.roidb_func(x, false),
        dataset.imdb_train, 'UniformOutput', false);

Error in Dataset.caltech_trainval (line 6)
        dataset.roidb_train   = cellfun(@(x) x.roidb_func(x, false),
        dataset.imdb_train, 'UniformOutput', false);

Error in script_rpn_pedestrian_VGG16_caltech (line 31)
dataset                     = Dataset.caltech_trainval(dataset, 'train');

Error in run (line 96)
evalin('caller', [script ';']);`

The demo script (script_rpn_bf_pedestrian_VGG16_caltech_demo) works fine, and I already run extract_img_anno.m to achieve train and test folder. Kindly give suggestion.

**Comment by brisker** [comment]
How did you solve this problem?
