### ISSUE TITLE
compilation error

### ISSUE THREAD

**Issue by clzhou** [zhangliliang/RPN_BF#7]
Hello!

When compiling the specified Caffe version, I got the following errors:
`/tmp/mex_9704849759849136_22812/caffe_.o: In function`mx_mat_to_blob(mxArray_tag const_, caffe::Blob<float>_, WhichMemory)':
caffe_.cpp:(.text+0x1674): undefined reference to `mxIsGPUArray'
caffe_.cpp:(.text+0x167d): undefined reference to`mxInitGPU'
caffe_.cpp:(.text+0x1685): undefined reference to `mxGPUCreateFromMxArray'
caffe_.cpp:(.text+0x1690): undefined reference to`mxGPUGetDataReadOnly'
caffe_.cpp:(.text+0x16a3): undefined reference to `mxGPUGetNumberOfElements'
caffe_.cpp:(.text+0x1854): undefined reference to`mxIsGPUArray'
caffe_.cpp:(.text+0x1860): undefined reference to `mxGPUDestroyGPUArray'
/tmp/mex_9704849759849136_22812/caffe_.o: In function`blob_set_data(int, mxArray_tag**, int, mxArray_tag const**)':
caffe_.cpp:(.text+0x18f8): undefined reference to `mxIsGPUArray'
collect2: error: ld returned 1 exit status`

Do you have any idea on how to fix them? Thanks.

**Comment by zhangliliang** [comment]
Hello,

Could you compile the official caffe branch on your computer?
And what's the environment on your computer?

**Comment by clzhou** [comment]
I just installed your caffe branch successfully on Ubuntu 14.04 + Matlab 2014a. 
The compilation of matlab APIs failed on Ubuntu 16.04 + Matlab 2014b where I have compiled the official caffe successfully.  I guess it may be something related to the use of mxGPUArray in the caffe_.cpp. To compile it, I have to explicitly add the following include directory to the Makefile.config: /usr/local/MATLAB/R2014b/toolbox/distcomp/gpu/extern/include. 
Otherwise, the compiler cannot find  gpu/mxGPUArray.h. Then, the above errors occurred.
Do you know which library should be linked against in order to use APIs like mxInitGPU?

**Comment by zhangliliang** [comment]
@clzhou 

I am sorry that I have not check out this repo on Ubuntu 16.04.
And currently I have no idea for fixing this issue.

**Comment by clzhou** [comment]
Thanks anyway.
