### ISSUE TITLE
compiling error and testing error with RPN_BF caffe on ubuntu14.04

### ISSUE THREAD

**Issue by brisker** [zhangliliang/RPN_BF#8]
after run "make all", the error looks like this:

CXX src/caffe/syncedmem.cpp
In file included from ./include/caffe/blob.hpp:9:0,
                 from src/caffe/blob.cpp:4:
./include/caffe/proto/caffe.pb.h:17:2: error: #error This file was generated by an older version of protoc which is
 #error This file was generated by an older version of protoc which is
  ^
./include/caffe/proto/caffe.pb.h:18:2: error: #error incompatible with your Protocol Buffer headers. Please
 #error incompatible with your Protocol Buffer headers.  Please
  ^
./include/caffe/proto/caffe.pb.h:19:2: error: #error regenerate this file with a newer version of protoc.
 #error regenerate this file with a newer version of protoc.

Then I simply run "pip install protobuf" and the error is gone, but when  I run "make test", there is a new error reads like this:

CXX src/gtest/gtest-all.cpp
src/caffe/test/test_im2col_kernel.cu(88): error: no instance of function template "caffe::im2col_cpu" matches the argument list
            argument types are: (const float *, int, int, int, int, int, int, int, int, int, float *)
          detected during:
            instantiation of "void caffe::Im2colKernelTest_TestGPU_Test<gtest_TypeParam_>::TestBody() [with gtest_TypeParam_=float]" 
./src/gtest/gtest.h(7209): here
......

2 errors detected in the compilation of "/tmp/tmpxft_00004d75_00000000-16_test_im2col_kernel.compute_50.cpp1.ii".
make: **\* [.build_release/cuda/src/caffe/test/test_im2col_kernel.o] 错误 1

Could you please give some advice? Thanks a lot!
@zhangliliang

**Comment by zhangliliang** [comment]
Hi,

This error might be that I only re-write the im2col in the layers but no re-write the corresponding test code.

You might try to make clean the project and use make (not make all, which might include the test part) for compiling the project.

**Comment by brisker** [comment]
I have tried "make -j6" and "make test -j6", but still the same error.
@zhangliliang

**Comment by brisker** [comment]
The error reads like this:
NVCC src/caffe/test/test_im2col_kernel.cu
CXX src/gtest/gtest-all.cpp
src/caffe/test/test_im2col_kernel.cu(88): error: no instance of function template "caffe::im2col_cpu" matches the argument list
            argument types are: (const float *, int, int, int, int, int, int, int, int, int, float *)
          detected during:
            instantiation of "void caffe::Im2colKernelTest_TestGPU_Test<gtest_TypeParam_>::TestBody() [with gtest_TypeParam_=float]" 
./src/gtest/gtest.h(7209): here
            implicit generation of "caffe::Im2colKernelTest_TestGPU_Test<gtest_TypeParam_>::~Im2colKernelTest_TestGPU_Test() [with gtest_TypeParam_=float]" 
./src/gtest/gtest.h(7209): here
            instantiation of class "caffe::Im2colKernelTest_TestGPU_Test<gtest_TypeParam_> [with gtest_TypeParam_=float]" 
./src/gtest/gtest.h(7209): here
            implicit generation of "caffe::Im2colKernelTest_TestGPU_Test<gtest_TypeParam_>::Im2colKernelTest_TestGPU_Test() [with gtest_TypeParam_=float]" 
./src/gtest/gtest.h(7209): here
            instantiation of class "caffe::Im2colKernelTest_TestGPU_Test<gtest_TypeParam_> [with gtest_TypeParam_=float]" 
./src/gtest/gtest.h(7209): here
            instantiation of "testing::Test *testing::internal::TestFactoryImpl<TestClass>::CreateTest() [with TestClass=caffe::Im2colKernelTest_TestGPU_Test<float>]" 
./src/gtest/gtest.h(7343): here
            implicit generation of "testing::internal::TestFactoryImpl<TestClass>::~TestFactoryImpl() [with TestClass=caffe::Im2colKernelTest_TestGPU_Test<float>]" 
./src/gtest/gtest.h(7343): here
            instantiation of class "testing::internal::TestFactoryImpl<TestClass> [with TestClass=caffe::Im2colKernelTest_TestGPU_Test<float>]" 
./src/gtest/gtest.h(7343): here
            implicit generation of "testing::internal::TestFactoryImpl<TestClass>::TestFactoryImpl() [with TestClass=caffe::Im2colKernelTest_TestGPU_Test<float>]" 
./src/gtest/gtest.h(7343): here
            instantiation of class "testing::internal::TestFactoryImpl<TestClass> [with TestClass=caffe::Im2colKernelTest_TestGPU_Test<float>]" 
./src/gtest/gtest.h(7343): here
            instantiation of "__nv_bool testing::internal::TypeParameterizedTest<Fixture, TestSel, Types>::Register(const char *, const char *, const char *, int) [with Fixture=caffe::Im2colKernelTest, TestSel=testing::internal::TemplateSel<caffe::Im2colKernelTest_TestGPU_Test>, Types=caffe::gtest_type_params_Im2colKernelTest_]" 
(70): here

src/caffe/test/test_im2col_kernel.cu(88): error: no instance of function template "caffe::im2col_cpu" matches the argument list
            argument types are: (const double *, int, int, int, int, int, int, int, int, int, double *)
          detected during:
            instantiation of "void caffe::Im2colKernelTest_TestGPU_Test<gtest_TypeParam_>::TestBody() [with gtest_TypeParam_=double]" 
./src/gtest/gtest.h(7209): here
            implicit generation of "caffe::Im2colKernelTest_TestGPU_Test<gtest_TypeParam_>::~Im2colKernelTest_TestGPU_Test() [with gtest_TypeParam_=double]" 
./src/gtest/gtest.h(7209): here
            instantiation of class "caffe::Im2colKernelTest_TestGPU_Test<gtest_TypeParam_> [with gtest_TypeParam_=double]" 
./src/gtest/gtest.h(7209): here
            implicit generation of "caffe::Im2colKernelTest_TestGPU_Test<gtest_TypeParam_>::Im2colKernelTest_TestGPU_Test() [with gtest_TypeParam_=double]" 
./src/gtest/gtest.h(7209): here
            instantiation of class "caffe::Im2colKernelTest_TestGPU_Test<gtest_TypeParam_> [with gtest_TypeParam_=double]" 
./src/gtest/gtest.h(7209): here
            [ 2 instantiation contexts not shown ]
            instantiation of class "testing::internal::TestFactoryImpl<TestClass> [with TestClass=caffe::Im2colKernelTest_TestGPU_Test<double>]" 
./src/gtest/gtest.h(7343): here
            implicit generation of "testing::internal::TestFactoryImpl<TestClass>::TestFactoryImpl() [with TestClass=caffe::Im2colKernelTest_TestGPU_Test<double>]" 
./src/gtest/gtest.h(7343): here
            instantiation of class "testing::internal::TestFactoryImpl<TestClass> [with TestClass=caffe::Im2colKernelTest_TestGPU_Test<double>]" 
./src/gtest/gtest.h(7343): here
            instantiation of "__nv_bool testing::internal::TypeParameterizedTest<Fixture, TestSel, Types>::Register(const char *, const char *, const char *, int) [with Fixture=caffe::Im2colKernelTest, TestSel=testing::internal::TemplateSel<caffe::Im2colKernelTest_TestGPU_Test>, Types=testing::internal::Types1<double>]" 
./src/gtest/gtest.h(7346): here
            instantiation of "__nv_bool testing::internal::TypeParameterizedTest<Fixture, TestSel, Types>::Register(const char *, const char *, const char *, int) [with Fixture=caffe::Im2colKernelTest, TestSel=testing::internal::TemplateSel<caffe::Im2colKernelTest_TestGPU_Test>, Types=caffe::gtest_type_params_Im2colKernelTest_]" 
(70): here

2 errors detected in the compilation of "/tmp/tmpxft_000040ba_00000000-16_test_im2col_kernel.compute_50.cpp1.ii".
make: *** [.build_release/cuda/src/caffe/test/test_im2col_kernel.o] 错误 1

**Comment by brisker** [comment]
But I found out that after I run "make clean', there is a line read like this:
bc: symbol lookup error: /anaconda2/lib/libreadline.so.6: undefined symbol: PC
Does this make sense for this error ? @zhangliliang

**Comment by brisker** [comment]
Did you mean that I do not need to run "make test" ?
@zhangliliang

**Comment by zhangliliang** [comment]
Yes, only `make` and `make mat`.

**Comment by zhangliliang** [comment]
@brisker 

I fix it via removing the test_im2col_kernel.cu
