### ISSUE TITLE
error when running script_rpn_pedestrian_VGG16_caltech.m for training rpn 

### ISSUE THREAD

**Issue by brisker** [zhangliliang/RPN_BF#9]
the error reads like this:
Loading region proposals...done
Warrning: no windows proposal is loaded !
引用了不存在的字段 'sizes'。

出错 roidb_from_caltech (line 52)
  height = imdb.sizes(1,1);

出错 Dataset.caltech_trainval>@(x)x.roidb_func(x,false) (line 6)
        dataset.roidb_train   = cellfun(@(x) x.roidb_func(x, false), dataset.imdb_train, 'UniformOutput', false);

出错 Dataset.caltech_trainval (line 6)
        dataset.roidb_train   = cellfun(@(x) x.roidb_func(x, false), dataset.imdb_train, 'UniformOutput', false);

出错 script_rpn_pedestrian_VGG16_caltech (line 30)
dataset                     = Dataset.caltech_trainval(dataset, 'train');
Here is the screenshot of the dataset, have I got something wrong?
Thanks a lot! @zhangliliang 
![image](https://cloud.githubusercontent.com/assets/13804492/18941496/4593cb30-8644-11e6-98b4-de020c64445f.png)
![image](https://cloud.githubusercontent.com/assets/13804492/18941498/4ec564de-8644-11e6-9f95-dea79edbbdda.png)
![image](https://cloud.githubusercontent.com/assets/13804492/18941623/4a5199bc-8645-11e6-8a47-a833c49e46f4.png)

**Comment by zhangliliang** [comment]
Hi.

You might manually remove those files in `imdb/cache`, which might be generated unsuccessfully before.

**Comment by brisker** [comment]
@zhangliliang 
thanks for your reply! And I am a little confused by the annotations of caltech pedestrian dataset. I am new to this. So if  I want to train cpn using my own dataset, I know that I need to provide the ground truth bounding box coordinates. But in set06_VOOO_I00029.txt it looks like this:
% bbGt version=3
person-fa 172 184 10 26 0 0 0 0 0 0 0
person-fa 188 188 8 24 0 0 0 0 0 0 0

What do these zeros mean?  If I want to use my own dataset, I also need to provide annotations in this txt format?

**Comment by zhangliliang** [comment]
@brisker 

This file is extracting using the dollar's toolbox. Thus you could find the meaning of these number in the toolbox.

For using your dataset, you might need to write your own imdb and roidb generation scripts, which suitable for your data form.

**Comment by brisker** [comment]
@zhangliliang 
I  use TITAN X GPU,
After nearly 20 hours why the training log stops at iteration 9920?(stops at yesterday afternoon..........)
![image](https://cloud.githubusercontent.com/assets/13804492/18981473/152fa2e8-8711-11e6-828d-ae4615bae26e.png)

**Comment by zhangliliang** [comment]
@brisker 

It seems that the training stop after iter 10000, since it save such a model.

You might check the error message which output in the matlab console.

**Comment by brisker** [comment]
@zhangliliang 
The matlab console look like this:
![image](https://cloud.githubusercontent.com/assets/13804492/18985144/1338e108-8729-11e6-899b-68a09217f30c.png)

I can not see any error there

**Comment by brisker** [comment]
@zhangliliang 
Is it supposed to be like this?
![image](https://cloud.githubusercontent.com/assets/13804492/19011906/73fb0c42-87d7-11e6-9ec2-f28577932aba.png)

**Comment by zhangliliang** [comment]
Yes.

**Comment by brisker** [comment]
@zhangliliang
Is the code for training rpn you provide soecific for pedestrian detection dataset，  or  it can be easily adapted to another dataset? If  I want to train a new rpn with my own defined model and my own dataset, could you please tell me where to fix the code you provide?（just a general step advice） thanks a lot, i am a fresh man

**Comment by brisker** [comment]
i can not understand why the annotations of the caltech pedestrian dataset so different from the pascal voc2007 dataset，with just four numbers for the ground truth bounding boxes，but the caltech so many more zeroes in it. So i got annotations for my own dataset in the style and format in pascal voc2007，so i do not know how to adapt to your code

**Comment by zhangliliang** [comment]
The RPN is suitable for detection for specified class like object proposal, pedestrian detection, car detector and so on.

You could find the meaning for zero in the dollar's toolbox. 

If you try to use your dataset, you might need to change the data preparing procedure and modified the relevant scripts.

**Comment by brisker** [comment]
@zhangliliang 
So what kind of object detection tasks does RPN perform better than faster-rcnn? What features do these tasks have in common?

**Comment by zhangliliang** [comment]
@brisker 

Hi,

These questions might be a little big and beyond the issue of this repo.

Recommend to read the original paper for this repo, and also the Faster/Fast R-CNN, SSD etc, to find out.

**Comment by brisker** [comment]
@zhangliliang 
In your paper you mentioined atrous convolution, where indicates that you use it in the code? In the prototxt?

**Comment by zhangliliang** [comment]
Yes.

In the prototxt when extracting feature for the BF trainning and testing.

**Comment by brisker** [comment]
@zhangliliang 
Two questions:
First, in the rpn_test.prototxt, I found the atours layer:
layer {
    bottom: "conv4_1_atrous"
    top: "conv4_2_atrous"
    name: "conv4_2_atrous"
    param {
        name: "conv4_2_w"
        lr_mult: 1.0
    }
    param {
        name: "conv4_2_b"
        lr_mult: 2.0
    }
    type: "Convolution"
    convolution_param {
        num_output: 512
        pad: 2
        kernel_size: 3
        filter_stride: 2
    }
}
I do not quite understand, so this layer's "type" is still "Convolution" ,so atrous convolution is not a new defined layer in caffe? Then how did it perform this?
![image](https://cloud.githubusercontent.com/assets/13804492/19031269/bdb9c65c-8985-11e6-8668-220a245eaed7.png)
Where to define the "rate=2"?

Second, in the paper , you mentioned that due to roipooling leads to "plain" features ,so you use atrous convolution, but in the train_val.prototxt for rpn training, I can not find roipooling layer? So what problem does atrous want to  solve? Just get feature maps from shallower layers?

**Comment by zhangliliang** [comment]
Hi, 

"rate=2" correspond to "filter_stride: 2" in the prototxt.

The atrous trick is not adopted during the RPN part, but the BF part.
